### ISSUE TITLE
Is CNAclinic also suitable for WES data?

### ISSUE THREAD

**Issue by wynstep** [sdchandra/CNAclinic#1]
I was wondering if this very great pipeline of analysis can be also adapted on Whole Exome Sequencing data, did you already performed any test?

Thank you!

**Comment by sdchandra** [comment]
Hi, this is used only for low coverage whole-genome sequencing. I can recommend EXCAVATOR2 or CopywriteR software if you want to look at CNAs in WES data

**Comment by yuanzhao0502** [comment]
Can I get the tumor fractions from CNAclinic for sWGS samples?
